import unittest
from mastermind_game import count_bulls_and_cows

class TestCountBullsAndCows(unittest.TestCase):
    '''
    Class of a Test Suite that tests the function of the Bulls and Cows.
    '''
    def test_all_bulls(self):
        '''
        Function that tests if the result generated by Bulls and Cows
        is corret when all bulls.
        '''
        secret_code = ['red', 'blue', 'green', 'yellow']
        current_guess = ['red', 'blue', 'green', 'yellow']
        result = count_bulls_and_cows(secret_code, current_guess)
        self.assertEqual(result, (4, 0))

    def test_all_cows(self):
        '''
        Function that tests if the result generated by Bulls and Cows
        is corret when all cows.
        '''
        secret_code = ['red', 'blue', 'green', 'yellow']
        current_guess = ['yellow', 'green', 'blue', 'red']
        result = count_bulls_and_cows(secret_code, current_guess)
        self.assertEqual(result, (0, 4))

    def test_mixed_bulls_and_cows(self):
        '''
        Function that tests if the result generated by Bulls and Cows
        is corret when mixed bulls and cows.
        '''
        secret_code = ['red', 'blue', 'green', 'yellow']
        current_guess = ['red', 'green', 'blue', 'yellow']
        result = count_bulls_and_cows(secret_code, current_guess)
        self.assertEqual(result, (2, 2))

    def test_no_bulls_or_cows(self):
        '''
        Function that tests if the result generated by Bulls and Cows
        is corret when no bulls or cows.
        '''
        secret_code = ['red', 'blue', 'green', 'yellow']
        current_guess = ['purple', 'black', 'orange', 'pink']
        result = count_bulls_and_cows(secret_code, current_guess)
        self.assertEqual(result, (0, 0))
def main():
    unittest.main(verbosity = 3)
if __name__ == "__main__":
    main()
